version: '3'

services:
  portifolia-api:
    container_name: portifolia-api
    build: '.'
    command: yarn start:dev
    volumes:
      - .:/home/node/portifolia-api
      - /home/node/portifolia-api/node_modules
    depends_on:
      - portifolia-postgres
    networks:
      - app-connect
    ports:
      - '5000:3000'
      - '5001:3001'

  portifolia-postgres:
    container_name: portifolia-postgres
    image: postgres:11
    restart: unless-stopped
    volumes:
      - portifolia-postgres-data:/data
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    networks:
      - app-connect

volumes:
  portifolia-postgres-data:

networks:
  app-connect:
    driver: bridge